---
title: "Experimental File for Tiff"
author: "Queenie Wei"
date: "2023-11-20"
output: pdf_document
---

```{r setup, include=FALSE}
library(raster)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(here)
#install.packages(sf)
library(sf)
?readTIFF

```


```{r}
here()
###loading biodiversity data
birdprioritization = raster(here("Biodiversity GIS data from Duke PhD doi_10/Vijay_et_al_2016_oilpalm_GISdata/birdprioritization.tif"))
mammalprioritization = raster(here("Biodiversity GIS data from Duke PhD doi_10/Vijay_et_al_2016_oilpalm_GISdata/mammalprioritization.tif"))

?here

suitableareapresent = raster(here("Biodiversity GIS data from Duke PhD doi_10/Vijay_et_al_2016_oilpalm_GISdata/suitableareapresent.tif"))
suitablearea2080 = raster(here("Biodiversity GIS data from Duke PhD doi_10/Vijay_et_al_2016_oilpalm_GISdata/suitablearea2080.tif"))

vulnerableforestpresent = raster(here("Biodiversity GIS data from Duke PhD doi_10/Vijay_et_al_2016_oilpalm_GISdata/vulnerableforestpresent.tif"))
vulnerableforest2080 = raster(here("Biodiversity GIS data from Duke PhD doi_10/Vijay_et_al_2016_oilpalm_GISdata/vulnerableforest2080.tif"))




oilpalmsamples <- st_read(here("Biodiversity GIS data from Duke PhD doi_10/Vijay_et_al_2016_oilpalm_GISdata/oilpalmsamplesites.shp"))
gfw_oil_palm <- st_read(here("gfw_oil_palm_v20191031.shp"))







plot(vulnerableforestpresent)
# plot(oilpalmsamples)
plot(gfw_oil_palm)
h = extract()
```